version: '3.2'

services:
    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
            - URL=nfler.se
            - SUBDOMAINS=www
            - VALIDATION=http
            - EMAIL=isaacpieber96@gmail.com
        volumes:
            - web-root:/config/www
        ports:
            - 443:443
            - 80:80
        restart: unless-stopped
        depends_on:
            - hot-coffee

    hot-coffee:
        image: nfler/hot-coffee
        container_name: hot-coffee
        volumes:
            - type: volume
              source: web-root
              target: /app/build

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --cleanup --remove-volumes
volumes:
    web-root:
