version: '3.2'

services:
    letsencrypt:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
            - URL=nfler.se
            - SUBDOMAINS=www,api
            - VALIDATION=http
            - EMAIL=isaacpieber96@gmail.com
        volumes:
            - web-root:/config/www
            - /opt/hot-coffee/nginx/nfler/letsencrypt:/config/etc/letsencrypt
            - nginx-conf:/config/nginx/site-confs/
        ports:
            - 443:443
            - 80:80
        restart: unless-stopped
        depends_on:
            - hot-coffee

    hot-coffee:
        image: nfler/hot-coffee
        container_name: hot-coffee
        volumes:
            - web-root:/app/build
            - nginx-conf:/app/nginx

    cold-coffee:
        image: nfler/cold-coffee
        container_name: cold-coffee
        ports:
            - 3000:3000

volumes:
    web-root:
    nginx-conf: