apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hot-coffee-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - {{ template "ingress.host" . }}
      secretName: nfler-tls
  rules:
    - host: {{ template "ingress.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hot-coffee-svc
                port:
                  number: {{ .Values.service.port }}