env:
  APP_NAME: 'hot-coffee'

name: CI/CD

on:
  push:
    branches: [ master ]

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        with:
         fetch-depth: 0
         
      - name: Bump version and push tag
        id: bumpver
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          
      - name: bumpver output
        run: echo ${{ steps.bumpver.outputs.new_tag }} ${{ steps.bumpver.outputs.tag }} ${{ steps.bumpver.outputs.part }}
        
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: nfler/${{ env.APP_NAME }}
          tags: |
           type=semver,pattern={{version}},value=${{ steps.bumpver.outputs.new_tag }}
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BUILD_MODE=prod
          tags: ${{ steps.meta.outputs.tags }}

      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN_K8S }}
          clusterName: k8s-nfler-dev
      
      - uses: azure/setup-helm@v1

      - name: Deploy with helm
        run: helm upgrade --set environment=production --set image.tag=${{ steps.meta.outputs.version }} ${{ env.APP_NAME }}-prod ./chart -i --create-namespace -n ${{ env.APP_NAME }}-prod

      