name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo 'Building docker image'
        docker build . --file Dockerfile --tag nfler/hot-coffee:latest
    - name: Login to dockerhub
      env:
        DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo 'Logging in to dockerhub'
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - name: Push to registry
      run: |
        echo 'Pushing to registry (dockerhub)'
        docker push nfler/hot-coffee:latest
        echo 'Done!'  
          
      
