# This is a basic workflow to help you get started with Actions

name: PR-Env
 
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: checkout code
        
      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        id: build-and-push
        with:
         image: nfler/hot-coffee
         registry: docker.io
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Echo image tag
        run: echo ${{ steps.build-and-push.outputs.imageName }}:${{ steps.build-and-push.outputs.tags }}
        
      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN_K8S }}
          clusterName: k8s-nfler-dev
      
      - uses: azure/setup-helm@v1

      - name: Deploy with helm
        run: helm upgrade --set image.tag=${{ steps.build-and-push.outputs.tags }} --set ingress.host=pr-${{ github.event.number }}.nfler.se hot-coffee-pr-${{ github.event.number }}- ./hot-coffee-chart -i --create-namespace -n hot-coffee-pr-${{ github.event.number }}


