name: PR-Env
 
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: checkout code
        
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: nfler/hot-coffee
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Echo image tag
        run: echo Tags ${{ steps.meta.outputs.tags }} Version ${{ steps.meta.outputs.version }} ${{ github.event.number }}
        
      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN_K8S }}
          clusterName: k8s-nfler-dev
      
      - uses: azure/setup-helm@v1

      - name: Deploy with helm
        run: helm upgrade --set image.tag=${{ steps.meta.outputs.version }} --set ingress.host=pr-${{ github.event.number }}.nfler.se hot-coffee-pr-${{ github.event.number }}- ./hot-coffee-chart -i --create-namespace -n hot-coffee-pr-${{ github.event.number }}


