name: CI/CD

on:
  push:
    branches: [ master ]

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run build
      uses: actions/setup-node@v1
    - run: |
        npm install
        npm run build

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'nfler'
        AWS_ACCESS_KEY_ID: ${{ secrets.CDN_NFLER_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CDN_NFLER_SECRET_KEY }}
        AWS_REGION: 'ams3'
        SOURCE_DIR: 'build'
        AWS_S3_ENDPOINT: 'https://nfler.ams3.digitaloceanspaces.com'
        DEST_DIR: 'static'
