name: CI/CD

on:
  push:
    branches: [ master ]

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: nfler/hot-coffee
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
