name: CI/CD

on:
  push:
    branches: [ master ]

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        id: build-and-push
        with:
         image: nfler/hot-coffee
         registry: docker.io
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Echo image tag
        run: echo ${{ steps.build-and-push.outputs.imageName }}:${{ steps.build-and-push.outputs.tags }}
        
      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN_K8S }}
          clusterName: k8s-nfler-dev

      - name: Get nodes
        run: kubectl set image deployment/hot-coffee-deployment hot-coffee=${{ steps.build-and-push.outputs.imageName }}:${{ steps.build-and-push.outputs.tags }} --record

      
