name: CI/CD

on:
  push:
    branches: [ master ]

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        id: build-and-push
        with:
         image: nfler/hot-coffee
         registry: docker.io
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Echo image tag
        run: echo ${{ steps.build-and-push.outputs.imageName }}
      
