name: CI/CD

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run build
        uses: actions/setup-node@v1
      - run: |
          npm install
          npm run build

      - name: Scp files to PR
        uses: appleboy/scp-action@master
        with:
          host:  ${{secrets.DEPLOY_HOST}}
          username: ${{secrets.DEPLOY_USERNAME}}
          key: ${{secrets.DEPLOY_SSH_KEY}}
          passphrase: ${{secrets.DEPLOY_SSH_PASSPHRASE}}
          source: "build/*"
          target: /opt/irish-coffee/nginx/nfler/www/pr-${{github.event.number}}
          rm: true
          strip_components: 1
