name: CI/CD

on:
  push:
    branches: [ master ]

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      name: Checkout repository
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
        
    - name: Git Version
      uses: codacy/git-version@2.2.0
      with:
        prefix: ${{ github.head_ref }}
      
      
    #- name: Set up QEMU
    #  uses: docker/setup-qemu-action@v1

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v1

    #- name: Login to DockerHub
    #  uses: docker/login-action@v1 
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}

    #- name: Build and push
    #  id: docker_build
    #  uses: docker/build-push-action@v2
    #  with:
    #    push: true
    #    tags: nfler/hot-coffee:latest

    #- name: Image digest
    #  run: echo ${{ steps.docker_build.outputs.digest }}
      
