name: CI/CD

on:
  push:
    branches: [ master ]

jobs:

  build-push-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo 'Building docker image'
        docker build . --file Dockerfile --tag nfler/hot-coffee:latest
    - name: Login to dockerhub
      env:
        DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo 'Logging in to dockerhub'
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - name: Push to registry
      run: |
        echo 'Pushing to registry (dockerhub)'
        docker push nfler/hot-coffee:latest
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        script: /opt/irish-coffee/deploy.sh
        host:  ${{secrets.HOST}}
        username: root
        key: ${{secrets.PRIVATE_KEY}}
        port: 22
