name: CI/CD

on:
  push:
    branches: [ master ]

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: nfler/hot-coffee
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
