name: CI/CD

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo 'Building docker image'
        docker build . --file Dockerfile --tag nfler/hot-coffee:latest
