env:
  APP_NAME: 'hot-coffee'

name: Uninstall pr environment

on:
  pull_request:
    types: [ closed ]

jobs:

  pr-env-remove:

    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN_K8S }}
          clusterName: k8s-nfler-dev
      
      - uses: azure/setup-helm@v1

      - name: uninstall with helm
        run: helm uninstall ${{ env.APP_NAME }}-pr-${{ github.event.number }} -n ${{ env.APP_NAME }}-pr-${{ github.event.number }}

      - name: delete namespace
        run: kubectl delete namespace ${{ env.APP_NAME }}-pr-${{ github.event.number }}

      